package com.example.cataniaunited.logic.dto

enum class MessageType {
    //Server Messages
    CONNECTION_SUCCESSFUL,
    CLIENT_DISCONNECTED,
    ERROR,
    LOBBY_UPDATED,
    PLAYER_JOINED,
    LOBBY_CREATED,
    GAME_BOARD_JSON,
    DICE_RESULT,
    GAME_WON,
    GAME_STARTED,
    ROBBER_PHASE,
    NEXT_TURN,

    //Client Messages
    CREATE_LOBBY,
    JOIN_LOBBY,
    LEAVE_LOBBY,
    SET_USERNAME,
    PLACE_SETTLEMENT,
    UPGRADE_SETTLEMENT,
    PLACE_ROAD,
    START_GAME,
    BUY_DEVELOPMENT_CARD,
    ROLL_DICE,
    PLACE_ROBBER,
    SET_READY,
    END_TURN
}